version: '3.5'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      PGDATA: /data/postgres
      POSTGRES_DB: urls
    ports:
      - "5431:5432"
    volumes:
      - postgres:/data/postgres

  urlshrinker:
    image: docker.io/library/urlshrinker:0.1.0-SNAPSHOT
    environment:
      DB_URL: postgresdb
      DB_USER: postgres
      DB_PASS: pass1234
      DB_NAME: urls
    ports:
      - "9000:8080"
    depends_on:
      - postgresdb
volumes:
  postgres:
